### ISSUE TITLE
Distribute throws EADDRNOTAVAIL

### ISSUE THREAD

**Issue by KeKs0r** [signicode/scramjet#10] opened 2018-09-20 11:05 UTC
Hi,

I stumbled upon your library and have to admit I really like it. A few more examples and more documentation would help a lot (willing to help her). But conceptually really great.

While playing around with it, I wanted to reduce the time, my processing takes in order to test more variations on my logic. When using the distribute function, I am getting the following error:

```
Error: listen EADDRNOTAVAIL 127.190.121.182
    at Object._errnoException (util.js:992:11)
    at _exceptionWithHostPort (util.js:1014:20)
    at Server.setupListenHandle [as _listen2] (net.js:1338:19)
    at listenInCluster (net.js:1396:12)
    at doListen (net.js:1505:7)
    at _combinedTickCallback (internal/process/next_tick.js:141:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
    at Function.Module.runMain (module.js:695:11)
    at startup (bootstrap_node.js:191:16)
    at bootstrap_node.js:612:3
```

My Pipeline looks like this:
```
const nodeStream = readStream.pipe(JSONStream.parse());
DataStream.from(nodeStream)
  .each(validate)
  .catch(console.error)
  .remap(makeRemap())
  .distribute(cpus, subprocess)
  .reduce(reduceSum, result)
  .then(writeToFile)
  .then(() => console.log(result))
  .catch(console.error)
  .then(() => console.timeEnd('process'));
```

Some of the functions are not in this code, so here is the gist with everything:
https://gist.github.com/KeKs0r/f44834378254b7a6a1a953759467648d

**Comment by MichalCz** [comment] 2018-09-20 12:03
Interesting, can you also add some info on your system?

It would be nice to see output from `ip a` and some general info. I'll look into this and try to reproduce.

**Comment by KeKs0r** [comment] 2018-09-20 12:42
I am running osx.
I tried to run my script on node 10.6.0 as well as 8.11.3.
What exactly do you mean with `ip a`?

**Comment by MichalCz** [comment] 2018-09-20 17:56
Hi,

Sadly we don't have a mac machine in an automated pipeline - that's one of the things to set up for us...

I think I won't be able to check this before Monday. I'll update with my findings...

**Comment by KeKs0r** [comment] 2018-09-20 20:15
Thanks a lot for looking into this. If i can help by providing some input or test something. Let me know.

**Comment by MichalCz** [comment] 2018-09-21 13:30
Well the reason for this is a different network stack or some permissions that doesn't allow me to use the whole 127.0.0.0/8 network.

In this case it's just a matter of identifying that condition and using a narrower range of ip's.

If you could change the line: 
https://github.com/signicode/scramjet/blob/master/lib/stream-worker.js#L42

to one of these:

```javascript
        this.ip = `127.0.${process.pid % 256}.${process.pid >> 8}`; // or
        this.ip = `127.0.0.${process.pid % 256}`;
        this.ip = `127.0.0.1`;
```

and tell me which one helped.

The code is on the list for a major rewrite in scramjet v5.

**Comment by KeKs0r** [comment] 2018-09-21 22:36
I tried all options and it seemed that only the last one is working:
```
this.ip = `127.0.0.1`;
```
But when running I am getting this error:
```
internal/child_process.js:675
    var string = JSON.stringify(message) + '\n';
                      ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:675:23)
    at process.target.send (internal/child_process.js:586:19)
    at process.on.e (/Users/marc/Workspace/mmm/node_modules/scramjet/lib/stream-child.js:71:47)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
internal/child_process.js:675
    var string = JSON.stringify(message) + '\n';
                      ^

TypeError: Converting circular structure to JSON
    at JSON.stringify (<anonymous>)
    at process.target._send (internal/child_process.js:675:23)
    at process.target.send (internal/child_process.js:586:19)
    at process.on.e (/Users/marc/Workspace/mmm/node_modules/scramjet/lib/stream-child.js:71:47)
    at emitTwo (events.js:126:13)
    at process.emit (events.js:214:7)
    at emitPendingUnhandledRejections (internal/process/promises.js:108:22)
    at process._tickCallback (internal/process/next_tick.js:189:7)
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at _errnoException (util.js:992:11)
    at WriteWrap.afterWrite [as oncomplete] (net.js:864:14)
```

**Comment by MichalCz** [comment] 2018-09-30 13:52
@KeKs0r can you try the new version and confirm it's fixed now?

**Closed** 2018-10-08 19:44 UTC
Labels: bug, fix released, mac
